services:
  - type: web
    name: voyageai-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx tsc --project tsconfig.json && ls -la dist/ && ls -la dist/
    startCommand: node dist/index.js
    autoDeploy: true
    envVars:
      - key: API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MAPBOX_ACCESS_TOKEN
        sync: false
      - key: GOOGLE_PLACES_KEY
        value: AIzaSyDyNmLKsGtPg19qVf2zUXQ6pJ-aesfb3HI
      - key: PEXELS_API_KEY
        value: f6yIcuxX3oe89a7HfevPg6ZHhthua7E4FxdttDNnkJhJkwEzOzDDr6nc
      - key: FOURSQUARE_API_KEY
        sync: false
      - key: PORT
        value: 3001
      - key: OPENAI_MODEL
        value: gpt-4o-mini